---
- name: installing aws cli
  include_tasks: aws-cli.yml
  
- name: Fetching IP to set targets
  include_tasks: fetchip.yml

- name: Install Prometheus
  include_tasks: prometheus.yml

- name: Install Alertmanager
  include_tasks: alertmanager.yml
