plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Name: "prometheus-server"
keyed_groups:
  - key: tags.Name
    prefix: tag_Name__
hostnames:
  - public_ip_address
  - private_ip_address
  - tag:Name
compose:
  ansible_host: public_ip_address
