plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:fetch_name: prometheus-instance
  instance-state-name: running
hostnames:
  - public-ip-address
compose:
  ansible_host: public-ip-address
