plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
keyed_groups:
  - key: tags.prometheus-server
    prefix: ""
  - key: instance_state
    prefix: state_
filters:
  instance-state-name: running
hostnames:
  - public-ip-address
compose:
  ansible_host: public-ip-address
